#!perl
sub on_user_command {
    my ($self, $cmd) = @_;
    if ($cmd eq "urxvt-color:day") {
        my $output = `/home/doom/.dynamic-colors/bin/dynamic-colors switch solarized-light`;
        $self->cmd_parse($output);
    }
    if ($cmd eq "urxvt-color:night") {
        my $output = `/home/doom/.dynamic-colors/bin/dynamic-colors switch solarized-dark`;
        $self->cmd_parse($output);
    }

}
